blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://dtpyappframework.readthedocs.io
    about: Check the documentation for answers to common questions
  - name: Security Issues
    url: https://github.com/Digital-Thought/dtPyAppFramework/blob/main/SECURITY.md
    about: Please report security vulnerabilities privately via email
